# syntax=docker/dockerfile:1
FROM node:14-alpine AS deps
WORKDIR /app

# 1er correctif : Mise à jour des paquets de l'OS pour l'étape de build
RUN apk upgrade --no-cache

COPY package.json package-lock.json ./
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci --omit=dev

FROM node:14-alpine AS runtime
WORKDIR /app

# 2ème correctif : Mise à jour des paquets de l'OS pour l'image finale (très important pour Trivy)
RUN apk upgrade --no-cache

COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node server.js db.js package.json ./

USER node
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/health || exit 1

CMD ["node", "server.js"]
