# syntax=docker/dockerfile:1
FROM node:22.11-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
# Montage du secret pendant le build uniquement
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci --omit=dev

FROM node:22.11-alpine AS runtime
WORKDIR /app
# On récupère uniquement le dossier node_modules de l'étape "deps" avec les bons droits
COPY --from=deps --chown=node:node /app/node_modules ./node_modules
# On copie uniquement le code nécessaire
COPY --chown=node:node server.js db.js package.json ./
# On utilise un utilisateur non root
USER node
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/health || exit 1
CMD ["node", "server.js"]
