name: CI Security Scan

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image
        run: docker build -f api/Dockerfile.multi -t demo-api:multi ./api

      - name: Scan Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'demo-api:multi'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
